jihan:
  name: jihan
  age: ${random.int(0,100)}
  fullName: ${jihan.name} Lee
spring:
  output:
    ansi:
      enabled: always
#logging:
#  file:
#    path: logs
#  level:
#    com:
#      yeonho:
#        springinit: DEBUG